<?php $clickheatConf = array (
  'logPath' => '/var/www/agdash/clickheat/logs/',
  'cachePath' => '/var/www/agdash/clickheat/cache/',
  'referers' => 
  array (
    0 => 'denbox',
  ),
  'groups' => false,
  'filesize' => 0,
  'adminLogin' => 'shelby',
  'adminPass' => '1584f3930d0df40b983cd214464cb876',
  'viewerLogin' => 'guest',
  'viewerPass' => '084e0343a0486ff05530df6c705c8bb4',
  'memory' => 64,
  'step' => 5,
  'dot' => 19,
  'flush' => 40,
  'start' => 'm',
  'palette' => false,
  'heatmap' => true,
  'hideIframes' => true,
  'hideFlashes' => true,
  'yesterday' => false,
  'alpha' => 80,
  'version' => '1.9-revB',
); ?>